extends Resource

class_name OrderItemInfo

enum Items { 
	MOON_JUICE,
	LUNAR_LATTE,
	SPACE_DUST_SMOOTHIE,
	METEORITE_MUFFIN,
	SOLAR_STACK,
	STARBERRIES,
	ASTROCAKES
}

var Prices = {
	Items.MOON_JUICE: 1,
	Items.LUNAR_LATTE: 1,
	Items.SPACE_DUST_SMOOTHIE: 2,
	Items.METEORITE_MUFFIN: 2,
	Items.SOLAR_STACK: 3,
	Items.STARBERRIES: 3,
	Items.ASTROCAKES: 4,
}
